# packages/atom_s3r/connectivity.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  ap:
    ssid: "Atom-S3R-BLE-IR-Proxy"
    password: "Y9iFn3hG8Akf"

  on_connect:
    then:
      - lambda: |-
          id(wifi_last_transition_ms) = millis();
      - component.update: display_1

  on_disconnect:
    then:
      - lambda: |-
          id(wifi_last_transition_ms) = millis();
      - component.update: display_1

captive_portal:

# Track IP / WiFi info (used for display background logic)
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Atom IP Address" 
      id: wifi_ip
    ssid:
      name: "Atom SSID"
      id: wifi_ssid

sensor:
  - platform: wifi_signal
    name: "Atom WiFi Signal"
    id: wifi_rssi
    update_interval: 30s

